import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import TawkToChat from "@/components/TawkToChat";
import Header from "@/components/home/Header";
import Footer from "@/components/home/Footer";

import { CartProvider } from "@/contexts/CartContext";
import { GoldRatesProvider } from "@/contexts/GoldRatesContext";

import "@/styles/cart.css";
import "@/styles/cart-page.css";
import "@/styles/header-search.css";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pradeep Jewellers",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body
        className="min-h-full flex flex-col"
        suppressHydrationWarning
      >
        {/* PROVIDER START */}
        <GoldRatesProvider>
          <CartProvider>
            <Header />

            <div suppressHydrationWarning key="app-root">
              {children}
            </div>

            <Footer />
            <TawkToChat />
          </CartProvider>
        </GoldRatesProvider>
        {/* PROVIDER END */}
      </body>
    </html>
  );
}