import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Script from "next/script";

import NavigationGuard from "@/components/NavigationGuard";
import TawkToChat from "@/components/TawkToChat";
import GoogleOneTapShell from "@/components/GoogleOneTapShell";
import Header from "@/components/home/Header";
import Footer from "@/components/home/Footer";

import { CartProvider } from "@/contexts/CartContext";
import { CustomerAuthProvider } from "@/contexts/CustomerAuthContext";
import { GoldRatesProvider } from "@/contexts/GoldRatesContext";

import data from "@/data/contactDatas.json";

import "@/styles/cart.css";
import "@/styles/cart-page.css";
import "@/styles/header-search.css";
import "./globals.css";

const goldRatesRefreshMs =
  (data.heroSection.rates.refreshIntervalMinutes ?? 5) * 60 * 1000;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pradeep Jewellers",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body
        className="min-h-full flex flex-col"
        suppressHydrationWarning
      >
        <Script
          id="bfcache-reload"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `window.addEventListener("pageshow",function(e){if(e.persisted)location.reload();});`,
          }}
        />
        <GoldRatesProvider refreshMs={goldRatesRefreshMs}>
          <CustomerAuthProvider>
            <CartProvider>
              <NavigationGuard />
              <Header />

              <div
                className="app-root flex flex-1 flex-col min-h-0 w-full"
                suppressHydrationWarning
                key="app-root"
              >
                {children}
              </div>

              <Footer />
              <GoogleOneTapShell />
              <TawkToChat />
            </CartProvider>
          </CustomerAuthProvider>
        </GoldRatesProvider>
      </body>
    </html>
  );
}
