import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import TawkToChat from "@/components/TawkToChat";
import GoogleOneTapShell from "@/components/GoogleOneTapShell";
import Header from "@/components/home/Header";
import Footer from "@/components/home/Footer";

// IMPORT PROVIDER
import { CustomerAuthProvider } from "@/contexts/CustomerAuthContext";
import { GoldRatesProvider } from "@/contexts/GoldRatesContext";

import data from "@/data/contactDatas.json";

import "./globals.css";

const goldRatesRefreshMs =
  (data.heroSection.rates.refreshIntervalMinutes ?? 5) * 60 * 1000;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pradeep Jewellers",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body
        className="min-h-full flex flex-col"
        suppressHydrationWarning
      >
        {/* PROVIDER START */}
        <GoldRatesProvider refreshMs={goldRatesRefreshMs}>
          <CustomerAuthProvider>
          <Header />

          <div suppressHydrationWarning key="app-root">
            {children}
          </div>

          <Footer />

          <TawkToChat />

          <GoogleOneTapShell />

          </CustomerAuthProvider>
        </GoldRatesProvider>
        {/* PROVIDER END */}
      </body>
    </html>
  );
}